name: convert
version: 2.1.2-dev
description: Utilities for converting between data representations.
homepage: https://github.com/dart-lang/convert

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  charcode: ^1.1.0
  typed_data: ^1.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0