name: convert
version: 2.1.2-dev
description: Utilities for converting between data representations.
homepage: https://github.com/dart-lang/convert

environment:
  sdk: '>=2.10.0-0 <2.10.0'

dependencies:
  charcode: ^1.1.0
  typed_data: ^1.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0

dependency_overrides:
  async:
    git: git://github.com/dart-lang/async.git
  boolean_selector:
    git: git://github.com/dart-lang/boolean_selector.git
  charcode:
    git: git://github.com/dart-lang/charcode.git
  collection:
    git: git://github.com/dart-lang/collection.git
  js:
    git:
      url: git://github.com/dart-lang/sdk.git
      ref: 2-10-pkgs
      path: pkg/js
  matcher:
    git: git://github.com/dart-lang/matcher.git
  meta:
    git:
      url: git://github.com/dart-lang/sdk.git
      ref: 2-10-pkgs
      path: pkg/meta
  path:
    git: git://github.com/dart-lang/path.git
  pedantic:
    git: git://github.com/dart-lang/pedantic.git
  pool:
    git: git://github.com/dart-lang/pool.git
  source_maps:
    git: git://github.com/dart-lang/source_maps.git
  source_map_stack_trace:
    git: git://github.com/dart-lang/source_map_stack_trace.git
  source_span:
    git: git://github.com/dart-lang/source_span.git
  stack_trace:
    git: git://github.com/dart-lang/stack_trace.git
  stream_channel:
    git: git://github.com/dart-lang/stream_channel.git
  string_scanner:
    git: git://github.com/dart-lang/string_scanner.git
  term_glyph:
    git: git://github.com/dart-lang/term_glyph.git
  test_api:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_api
  test_core:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test_core
  test:
    git:
      url: git://github.com/dart-lang/test.git
      ref: null_safety
      path: pkgs/test
  typed_data:
    git: git://github.com/dart-lang/typed_data.git
